---
title: "Data Analysis Skills – Group Project 2"
number-sections: true
format: 
  html:
    embed-resources: true
    code-tools: true
  pdf: default
editor_options: 
  chunk_output_type: console
Author: Group 19
---

# **Generalised Linear Model**

Given the nature of our response variable (time_at_shelter), which counts the number of days, a Poisson regression could initially be considered. However, considering the clear over-dispersion (indicated by the presence of outliers), a negative binomial regression may be more appropriate. Negative binomial regression will continue to be used to fit the GLM given the skewness and potential over-dispersion of the count data.

```{r}
# Generalised Linear Model (GLM) with Negative Binomial Distribution 
library(MASS) 
model_nb <- glm.nb(time_at_shelter ~ animal_type + intake_type + outcome_type + chip_status, data = shelter) 
summary(model_nb)
```

From the summary of Generalised Linear Model (GLM) with Negative Binomial Distribution, we prove that the coefficient of intake_typeOWNER SURRENDER = -1.68925, P-value \< 2e-16, which indicates that animals surrendered by their owners tend to have shorter stays at the shelter compared to other intake types. The coefficient of Intake Type - Stray = -1.33821, P-value \< 2e-16, which indicates that stray animals spend less time at the shelter. The coefficient of Outcome Type - Died = -0.87955, P-value = 0.000214, which indicates that animals that die at the shelter have a shorter length of stay. The coefficient of Outcome Type - Euthanized = -0.73928, P-value \< 2e-16, which indicates that euthanized animals have shorter stays at the shelter. The coefficient of Outcome Type - Foster = -0.45149, P-value = 0.006737, which indicates that animals placed in foster care tend to have shorter lengths of stay at the shelter. The coefficient of Outcome Type - Returned to Owner = -1.63708, P-value \< 2e-16, which indicates that animals returned to their owners spend less time at the shelter. The coefficient of Chip Status - Scan No Chip = -0.15196, P-value = 0.030393, which indicates that animals without a microchip scan have a slightly shorter stay at the shelter. And other variables showed higher P-values, indicating that their relationship with the length of stay at the shelter is not as significant.
